### PR TITLE
semi working for 6.5.4

### PR DESCRIPTION
**Pull request by porkiz**
Semi Working for kibana 6.5.4.

Will fix the relevant bugs in the future.

### CODE REVIEW

**Comment by clamarque** [comment]
Hi @porkiz , thank for help me. My job take so much time... Which bug do u have with this version ?

**Comment by porkiz** [comment]
Hi @clamarque,

healthmetric
The font style is not the same as the normal metric.

sidebar
The control panel will not reflect changes properly.

I will try to resolve these issues when I can take some time off work.

**Comment by kamira** [comment]
image
It will be crash when vis version is 4.16.1.

**Comment by clamarque** [comment]
@porkiz  I close this PR. I push my version with only the useful features. Thank you for helping me 👍

**Pull request closed without merging**
