### PR TITLE
Update plugin to support Kibana 5

### PR DESCRIPTION
**Pull request by calston**
This is a breaking update to support working on Kibana 5.

### CODE REVIEW

**Comment by clamarque** [comment]
@calston Hi. Thanks for your work! I think you tested, right?

**Comment by calston** [comment]
Yes, have tested and we're using it. Is there a unit-test framework for this stuff? Bleh, Javascript. _Sadface_

**Comment by calston** [comment]
Only tested with Kibana 5.0 at least, there's no forwards/backwards compatibility with their awesome plugin framework

**Comment by clamarque** [comment]
@calston For unit-test framework, don't know. It is true that it is a pity that there is no compatibility between the differentes versions.

**Comment by clamarque** [comment]
@calston Hi. I try to install your modifications and i get this error: No kibana plugins found in archive". I use Kibana 5.0.0 and your archive directly.

**Comment by calston** [comment]
Plugins have moved to /usr/share/kibana/plugins from where it used to be. Not sure if the remote install works still?

**Comment by clamarque** [comment]
@calston I solved this. I will commit soon.

**Pull request merged**
